blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, toggle_activity

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
    path('activity/<int:pk>', toggle_activity, name='toggle_activity'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='заголовок')
    slug = models.CharField(max_length=150, **NULLABLE, verbose_name='slug')
    content = models.TextField(**NULLABLE, verbose_name='содержимое')
    preview = models.ImageField(upload_to='main/', **NULLABLE, verbose_name='превью (изображение)')
    creation_date = models.DateField(**NULLABLE, verbose_name='дата создания')
    publication_attribute = models.BooleanField(default=True, verbose_name='признак публикации')
    number_views = models.IntegerField(default=0, verbose_name='количество просмотров')

    def __str__(self):
        return f'{self.title} {self.number_views}'

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

blog/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.utils.text import slugify
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from blog.models import Blog


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'preview', 'content', 'creation_date',)
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(publication_attribute=True)

        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.number_views += 1
        self.object.save()

        return self.object


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'preview', 'content', 'creation_date',)

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list')


def toggle_activity(request, pk):
    blog_item = get_object_or_404(Blog, pk=pk)
    if blog_item.publication_attribute:
        blog_item.publication_attribute = False
    else:
        blog_item.publication_attribute = True

    blog_item.save()

    return redirect(reverse('blog:list'))

blog/templates/blog/blog_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить материал "{{ object.title }}"?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'blog:list' %}" class="btn btn-warning"> Отмена </a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">
                        Блог "{{ object.title }}" ({{ object.slug }})</h5>
                </div>
                <div class="card-body">
                    <p>
                        "{{ object.content }}"
                    <div class="card-footer>">
                        Содержимое: {{ object.content }}
                    </div>
                    </p>
                    <p>
                        "{{ object.creation_date }}"
                    <div class="card-footer>">
                        Просмотры: {{ object.number_views }}
                    </div>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                        {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'main/base.html' %}

{% block content %}

<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'blog:create' %}">Добавить блог</a>
</div>
{% for object in object_list %}
<div class="col-md-4">
    <div class="card h-95 w-90 text-bg-info mb-5 box-shadow" style="max-width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">{{ object.title }}</h5>
            <h6 class="card-title">Описание</h6>
            <p class="card-text">{{ object.content }}</p>
            <div class="btn-group" role="group" aria-label="Basic mixed styles example" style="width: 16rem;">
                <a href="{% url 'blog:view' object.pk %}"
                   class="btn btn-success">View</a>
                <a href="{% url 'blog:edit' object.pk %}" type="button"
                   class="btn btn-warning">Edit</a>
                <a href="{% url 'blog:delete' object.pk %}" type="button"
                   class="btn btn-danger">Delete</a>
            </div>
            {% if object.publication_attribute %}
            <a class="btn btn-warning" href="{% url 'blog:toggle_activity' object.pk %}">Negative</a>
            {% else %}
            <a class="btn btn-success" href="{% url 'blog:toggle_activity' object.pk %}">Positive</a>
            {% endif %}
        </div>
    </div>
</div>
{% endfor %}
</div>
{% endblock %}