blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, toggle_activity

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
    path('activity/<int:pk>', toggle_activity, name='toggle_activity'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import CategoryListView, ProductListView, ProductCategoryListView, ProductCardListView, \
    ProductCreateView, ProductUpdateView, toggle_activity

app_name = MainConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='product'),
    path('category/', CategoryListView.as_view(), name='category'),
    path('<int:pk>/main/', ProductCategoryListView.as_view(), name='products_categories'),
    path('<str:name>/main/', ProductCardListView.as_view(), name='product_card'),
    path('create/', ProductCreateView.as_view(), name='create_products'),
    path('<int:pk>/main/update/', ProductUpdateView.as_view(), name='update_products'),
    path('activity/<int:pk>/', toggle_activity, name='toggle_activity'),
]

main/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='наименование')
    description = models.TextField(**NULLABLE, verbose_name='описание')

    def __str__(self):
        return f'{self.name} ({self.description})'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    name = models.CharField(max_length=150, verbose_name='наименование')
    description = models.TextField(**NULLABLE, verbose_name='описание')
    price = models.IntegerField(default=0, verbose_name='цена за покупку')
    photo = models.ImageField(upload_to='main/', **NULLABLE, verbose_name='изображение')
    birth_day = models.DateField(**NULLABLE, verbose_name='дата создания')
    last_change = models.DateField(**NULLABLE, verbose_name='дата последнего изменения')
    category = models.CharField(max_length=150, verbose_name='категория')
    publication_attribute = models.BooleanField(default=True)
    number_views = models.IntegerField(default=0, verbose_name='количество просмотров')

    def __str__(self):
        return f'Наименование товара: {self.name},' \
               f'Описание: {self.description}),' \
               f'Количество просмотров: {self.number_views}'

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    @property
    def active_version(self):
        return self.product_ver.filter(name_current_version=True).exists()


class Version(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE, verbose_name='product', related_name='product_ver')

    name_version = models.CharField(max_length=150, verbose_name='название версии')
    number_version = models.IntegerField(default=1, verbose_name='номер версии')
    name_current_version = models.BooleanField(default=False, verbose_name='признак текущей версии')

    def __str__(self):
        return f'{self.name_version} ({self.name_current_version}), ({self.number_version})'

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'

main/views.py
from django.forms import inlineformset_factory
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView

from main.form import ProductForm
from main.models import Category, Product, Version


class CategoryListView(ListView):
    model = Category
    extra_context = {
        'title': 'Категории'
    }


class ProductListView(ListView):
    model = Product

    @staticmethod
    def all_version():
        return Version.objects.all()


class ProductCategoryListView(ListView):
    model = Product

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(category=self.kwargs.get('pk'))
        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)

        products_item = Category.objects.get(pk=self.kwargs.get('pk'))
        context_data['title'] = f'Товары из выбранной категории {products_item.name}'

        return context_data


class ProductCardListView(ListView):
    model = Product
    template_name = 'main/product_categories.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(pk=self.kwargs.get('pk'))
        return queryset

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.number_views += 1
        self.object.save()
        return self.object


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('main:product')


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('main:product')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, fields=['name_version', 'name_current_version'],
                                               extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


def toggle_activity(request, pk):
    product_item = get_object_or_404(Version, pk=pk)
    if product_item.name_current_version:
        product_item.name_current_version = False
    else:
        product_item.name_current_version = True

    product_item.save()

    return redirect(reverse('main:product'))

main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">


    <title>{{ title }}</title>


    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
</head>

<body>

<header>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <div class="container-fluid">
            <span class="navbar-toggler-icon"></span>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'main:category' %}">Категории</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:product' %}">Товары</a>
                     </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'blog:list' %}">Блог</a>
                </ul>
            </div>
        </div>
    </nav>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
            aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    </div>
    </div>
</header>

<main role="main">

    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">{{ title }}</h1>

        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">

            <div class="row">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>

</main>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
        <p>&copy; {% now 'Y' %}</p>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

main/templates/main/category.html
{% extends 'main/base.html' %}
{% block content %}
{% for object in object_list %}
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <p class="card-text">{{ object }}</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href ="{% url 'main:products_categories' object.pk %}" type="button" class="btn btn-dark">К товарам</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

main/templates/main/category_list.html
{% extends 'main/base.html' %}

{% block content %}


<div class="col-12 mb-5">
    <a class="btn btn-primary" href="{% url 'main:create_products' %}"
       class="btn btn-success">Добавить продукт</a>
</div>
{% load my_tags %}

{% for object in object_list %}
<div class="col-md-4">
    <div class="card h-95 w-90 text-bg-light mb-4 box-shadow" style="max-width: 18rem;">
        <!--        <img src="/media/{{ object.photo }}" />-->
        <img src="{{ object.photo|mediapath }}"/>
        <div class="card-body">
            <h5 class="card-title">{{ object.name }}</h5>
            <h6 class="card-title">Описание</h6>
            <p class="card-text">{{ object.description|truncatewords:4 }}</p>
            <div class="btn-group">
                <a href="{% url 'main:product_card' object.pk %}"
                   class="btn btn-success">Подробнее</a>
                <a href="{% url 'main:update_products' object.pk %}"
                   class="btn btn-success">Редактировать</a>
            </div>
        </div>
    </div>
</div>
{% endfor %}
</div>
{% endblock %}

main/templates/main/product.html
{% extends 'main/base.html' %}

{% block content %}
{% load my_tags %}
{% for object in product_list %}
<div class="col-md-4">
    <div class="card h-95 w-90 text-bg-light mb-4 box-shadow" style="max-width: 15rem;">
        <!--        <img src="/media/{{ object.photo }}" />-->
        <img src="{{ object.photo|mediapath }}"/>
        <div class="card-body">
            <h5 class="card-title">{{ object.name }}</h5>
            <h6 class="card-title">Описание</h6>
            <p class="card-text">{{ object.description|truncatewords:4 }}</p>
            <a href="{% url 'main:product_card' object.name %}" type="button" class="btn btn-dark">Полное описание</a>
        </div>
    </div>
</div>
{% endfor %}
</div>
</div>
{% endblock %}

main/templates/main/product_card.html
{% extends 'main/base.html' %}

{% block content %}
{% load my_tags %}
{% for object in product_list %}
<div class="col-md-4">
    <div class="card h-95 w-90 text-bg-light mb-4 box-shadow" style="max-width: 18rem;">
        <!--        <img src="/media/{{ object.photo }}" />-->
        <img src="{{ object.photo|mediapath }}"/>
        <div class="card-body">
            <h5 class="card-title">{{ object.name }}</h5>
            <h6 class="card-title">Описание</h6>
            <p class="card-text">{{ object.description}}</p>
            <h6 class="card-title">Цена</h6>
            <p class="card-text">{{ object.price}} руб.</p>
            <h6 class="card-title">Версия</h6>
            {% for version in object.product_ver.all %}
            {% if version.name_current_version %}
            <b>Наименование версии:</b> {{ version.name_version }}
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

main/templates/main/product_categories.html
{% extends 'main/base.html' %}

{% block content %}
{% load my_tags %}
{% for object in object_list %}
<div class="col-md-4">
    <div class="card h-95 w-90 text-bg-primary mb-4 box-shadow" style="max-width: 18rem;">
        <!--        <img src="/media/{{ object.photo }}" />-->
        <img src="{{ object.photo|mediapath }}"/>
        <div class="card-body">
            <h5 class="card-title">{{ object.name }}</h5>
            <h6 class="card-title">Описание</h6>
            <p class="card-text">{{ object.description}}</p>
            <h6 class="card-title">Цена</h6>
            <p class="card-text">{{ object.price}} руб.</p>
            {% for version in object.product_ver.all %}
            {% if version.name_current_version %}
            <b>Версия:</b> {{ version.name_version }}
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endfor %}
</div>
</div>
{% endblock %}

main/templates/main/product_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        {% if object %}
                        Редактирование продукта
                        {% else %}
                        Создание продукта
                        {% endif %}
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
</div>
<div class="col-6">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">

                {% if object %}
                Версии продукта
                {% else %}
                Первоначальное создание продукта
                {% endif %}
            </h3>
        </div>
        <div class="card-body">
            {{ formset.management_form }}
            {% for form in formset.forms %}
            {{ form.as_p }}
            {% endfor %}
        </div>
        <div class="card-footer"></div>
    </div>
    </form>
</div>
{% endblock %}

main/templates/main/product_list.html
{% extends 'main/base.html' %}

{% block content %}


<div class="col-12 mb-5">
    <a class="btn btn-primary" href="{% url 'main:create_products' %}"
       class="btn btn-success">Добавить продукт</a>
</div>
{% load my_tags %}

{% for object in object_list %}
<div class="col-md-4">
    <div class="card h-95 w-90 text-bg-light mb-4 box-shadow" style="max-width: 18rem;">
        <!--        <img src="/media/{{ object.photo }}" />-->
        <img src="{{ object.photo|mediapath }}"/>
        <div class="card-body">
            <h5 class="card-title">{{ object.name }}</h5>
            <h6 class="card-title">Описание</h6>
            <p class="card-text">{{ object.description|truncatewords:4 }}</p>
            <div class="btn-group">
                <a href="{% url 'main:product_card' object.pk %}"
                   class="btn btn-success">Подробнее</a>
                <a href="{% url 'main:update_products' object.pk %}"
                   class="btn btn-warning">Редактировать</a>
            </div>
        </div>
    </div>
</div>
{% endfor %}
</div>
{% endblock %}